name: Build

on:
  push:
    branches: [main]

jobs:
  packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@main

      - id: get-packages
        run: |
          set -Eeu
          packages="$(nix flake show --json github:diniamo/niqspkgs/${{ github.ref }} | jq --compact-output '.packages."x86_64-linux" | keys_unsorted | map("packages.x86_64-linux.\(.)")')"
          echo -n "packages=$packages" >> "$GITHUB_OUTPUT"

  build:
    needs: packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix build --print-build-logs github:diniamo/niqspkgs/${{ github.ref }}#${{ matrix.package }}
      - uses: cachix/cachix-action@v15
        with:
          name: niqspkgs
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
